import type { Metadata } from "next";
import { Roboto_Mono as Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import LayoutWrapper from "@/app/LayoutWrapper";

const roboto = Roboto({
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <LayoutWrapper>
          <Header /> {/* Move Header inside LayoutWrapper */}
          {children}
          <Footer /> {/* Move Footer inside LayoutWrapper if it also uses Redux */}
        </LayoutWrapper>
      </body>
    </html>
  );
}